# Site Settings
locale: "en-US"
title: "Yang Luo / PhD student in geochemistry"
title_separator: "-"

# Technical Configuration
url: "https://yangluo-geol.github.io"
baseurl: ""
repository: "yangluo-geol/yangluo-geol.github.io"
markdown: kramdown

# Plugins (Required for GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

# Collections
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
    sort_by: date
    sort_direction: descending
  publications:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: false
      share: true
      comments: false

# Author Information
author:
  name: "Yang Luo"
  avatar: "profile.jpg"
  bio: "Ph.D. Candidate in geochemistry"
  location: "Department of Earth Science, UC Santa Barbara"
  email: "yangluo@ucsb.edu"
  uri: "https://yangluo-geol.github.io"
  pronouns: "he/him"
  employer: "University of California, Santa Barbara"
  googlescholar: "https://scholar.google.com/citations?user=IOaZk2AAAAAJ"

# Research Information
research_interests:
  - "petrology"
  - "geochronology"
  - "geochemistry"

methods:
  - "SEM"
  - "EPMA"
  - "LA-ICP-MS"
