# ========================
# Site Metadata
# ========================
name: "Yang Luo"
title: "Yang Luo | PhD Student in Geochemistry"
description: "PhD candidate specializing in petrology and geochemistry at UC Santa Barbara"
locale: "en-US"
timezone: "America/Los_Angeles"
title_separator: "-"

# ========================
# Technical Configuration
# ========================
url: "https://yangluo-geol.github.io"
baseurl: ""
repository: "yangluo-geol/yangluo-geol.github.io"
markdown: kramdown
highlighter: rouge
future: true
show_drafts: false

# ========================
# Build Settings
# ========================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# ========================
# Collections Configuration
# ========================
collections:
  teaching:
    output: true
    permalink: /teaching/:name/
    sort_by: date
    sort_direction: descending
    show_collection_links: true
    
  publications:
    output: true
    permalink: /publications/:year-:title/
    
  talks:
    output: true

# ========================
# Default Values
# ========================
defaults:
  - scope:
      path: "_pages/teaching.html"
    values:
      layout: single
      permalink: /teaching/
      author_profile: false
      share: true
      comments: false
      toc: false
      
  - scope:
      path: "_pages/teaching.html"
    values:
      layout: single
      title: "Teaching Experience"
      permalink: /teaching/

# ========================
# Author Information
# ========================
author:
  name: "Yang Luo"
  avatar: " /tree/master/images/profile.jpg"
  bio: "Ph.D. Candidate in Geochemistry"
  location: "Department of Earth Science, UC Santa Barbara"
  email: "yangluo@ucsb.edu"
  uri: "https://yangluo-geol.github.io"
  pronouns: "he/him"
  employer: "University of California, Santa Barbara"
  
  # Academic Profiles
  googlescholar: "https://scholar.google.com/citations?user=IOaZk2AAAAAJ"
  
  # Social Media
  github: "yangluo-geol"
  linkedin: "" # Add if desired

# ========================
# Research Configuration
# ========================
research:
  interests:
    - "Petrology"
    - "Geochronology"
    - "Geochemistry"
    - "Mineralogy"
    
  methods:
    - "Scanning Electron Microscopy (SEM)"
    - "Electron Probe Microanalysis (EPMA)"
    - "Laser Ablation ICP-MS"
    - "X-ray Diffraction (XRD)"
    - "Optical Microscopy"

# ========================
# Publication Settings
# ========================
publication_types:
  - name: "Journal Articles"
    tag: "journal"
    icon: "far fa-file-alt"
    
  - name: "Conference Papers"
    tag: "conference" 
    icon: "fas fa-comments"

# ========================
# UI/Display Settings
# ========================
theme_settings:
  primary_color: "#2a7ae2"  # UCSB navy blue
  accent_color: "#ffd200"   # UCSB gold
  font:
    text: "Helvetica, Arial, sans-serif"
    code: "Courier, monospace"
    
  navbar:
    sticky: true
    logo: "assets/images/logo.png" # Optional
    
  footer:
    show_copyright: true
    show_powered_by: true

# ========================
# Analytics & SEO
# ========================
google_analytics: "" # Add your GA tracking ID
google_site_verification: "" # For search console

include:
  - _pages

