# Basic Site Settings
locale: "en-US"
site_theme: "default"

title: "Yang Luo / PhD student in geochemistry"
title_separator: "-"

# Site URLs
url: "https://yangluo-geol.github.io"       # Your GitHub Pages URL
baseurl: ""                    # Subpath of your site, if any

repository: "yangluo-geol/yangluo-geol"

# Site Author - sidebar info
author:
  avatar: "profile.jpg"
  name: "Yang Luo"
  pronouns: "he/him"
  bio: "Ph.D. Candidate in geochemistry"
  location: "Department of Earth Science, UC Santa Barbara"
  employer: "University of California, Santa Barbara"
  uri: "https://yangluo-geol.github.io"
  email: "yangluo@ucsb.edu"

# Academic websites
  googlescholar: "https://scholar.google.com/citations?user=IOaZk2AAAAAJ&hl=en&oi=sra"
  # Add other profiles here if needed:
  # academia: ""
  # arxiv: ""
  # inspire-hep: ""
  # impactstory: ""
  # orcid: ""

# Academic branding - research interests and methods
research_interests:
  - "petrology"
  - "geochronology"
  - "geochemistry"

methods:
  - "SEM"
  - "EPMA"
  - "LA-ICP-MS"

# Publication categories
publication_category:
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Comments (example Discourse or Facebook config)
comments:
  # discourse:
  #   server: ""
  facebook:
    appid: ""
    num_posts: 5
    colorscheme: "light"

staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
